Marcos Galindo

**PROYECCIÓN VECTORIAL**

La proyección vectorial es aplicada entre dos vectores (entes de n dimesiones, con cada dimensión definida por objetos que son escalares), sean dichos vectores **a** y **b**, entonces la proyección vectorial del vector **a** sobre el vector **b** es es un vector con dirección igual u opuesta **b**, este tendra como magnitud igual a la proyección del vector **a** sobre **b**. Esta puede ser entendida como la sombra que el vector **a** proyecta sobre el vector **b** al momento de tener una lampara sobre el vector **a** ubicada perpendicular al vector **b**.

In [10]:
import numpy as np

a=np.array([2,3,4])
b=np.array([3,4,5])
b_magnitude=(sum(np.square(b)))**0.5
c=b/b_magnitude

print(np.dot(a,b)*c)

[16.12203461 21.49604615 26.87005769]


**DEFINICIÓN**

La proyección vectorial del vector **a** sobre el vector **b** es un vector igual a 

vec_project= (a·b)*b_u

donde **a·b**  es el producto punto entre **a** y **b**, y  **b_u** es un vector con la misma dirección de **b** pero tiene magnitud uno (1). 

Esta puede ser definida en una función como se muestra a continuación:


In [9]:
def projec_vect_left_on_right(x,y):
    punto=np.dot(x,y)
    uni_vect=y/(np.sqrt(np.sum(np.square(y))))
    return punto*uni_vect/(np.sqrt(np.sum(np.square(y))))

a=np.array([2,3,4])
b=np.array([3,4,5]) 

projec_vect_left_on_right(a,b)

array([2.28, 3.04, 3.8 ])

**INTERPRETACIÓN**

La projección vectorial puede ser interpretada como se mencionó en el primer párrafo, es un vector con medida igual a la sombre proyectada de **a** sobre **b**, y con sentido igual a **b**.

In [28]:
a=np.array([2,3,4])
b=np.array([3,4,5])

projec_vect_left_on_right(a,b)

array([16.12203461, 21.49604615, 26.87005769])

El resultado anterior puede ser interpretado como un un vector con dicha dimensión que es paralelo a **b** y que posee su misma dirección. 

**PRODUCTO CRUZ**

Este es otro objeto que nos ayuda a medir como se comportan dos vectores. Este se define como una especie de  determinante de una matrix que posee como primer fila cada uno de los vectores unitarios en las dimensiones que se esten trabjando, luego en segunda y tercera fila, se tienen las componentes del primer vector y segundo vector respectivamente. Cabe mencionar que la idea y concepto de Producto cruz, se encuentra definido únicamente en tercera y séptima dimensión. 

**DEFINICIÓN**

In [14]:
def producto_cruz(x,y):
    return np.cross(x,y)

a=np.array([2,3,4])
b=np.array([3,4,5])

producto_cruz(a,b)

array([-1,  2, -1])

**INTERPRETACION**

Este en tres dimensiones, se puede interpretar como un vector perpendicular a dos vectores dados y tiene una magnitud igual al area formada por un paralelogramo constuido con los vectores dados y sus direcciones. Cabe mencionar que esta operaciones no es commutativa. 



**USO DE PRODUCTO DICHAS OPERACIONES EN MACHINE LEARNING**

Al momento de realizar una projección vectorial, ocurre un mapeo de una dimensión mayor hacia una ya conocida de menor dimensión. Esto puede ser empleado al momento de querer visualizar data o simplificarun problema en una dimensión mayor. 
Entre estas se puede mencionar Neural Networks, en el cual se busca poder encontrar o producir un vector que se asemeje lo más posible dada una base de datos, en este proceso se comparará por medio de las neuronas si éstas se parecen más a un vector al compararlos por medio de la proyección vectorial, la cual en sí se puede interpretar como una forma de compara que tan igual son dos vectores entre sí.

**CONCLUSIONES**

Se puede entender que la proyección vectorial es una herramienta muy sencilla que permite poder realizar analisis con una cantidad basta de aplicaciones. Como lo es en Neuronal Nerwork, en ellas se hace uso de proyección vectorial para poder pedir que tan parecidos son dos vectores dados. Al momento de querer comparar dos vectores y su similitud, esto nos permite ver y poder acoplar información a necesidades que tengamos. Como lo puede ser comparar una información con vectores que representen perdidas en un negocio, una imagen de un objeto que se busca, buscar tendencias en comportamientos de mercado, reconocimiento de voz, etc. 